### PR TITLE
introduce get_array_reply() to represent arrays

### PR DESCRIPTION
**Pull request by gquintard**
Hi,

We have a use case were filter rules are pushed into `redis` and we want to retrieve a flat file to parse it in one go, so here's a patch to do this.

This targets `6.0` as this is the main platform at the moment, but if this gets merged I'll be happy to open a PR for `6.3`/`master` too.

I'm not experienced with `redis` so all feedback is more than welcome

### CODE REVIEW

**Comment by carlosabalde** [comment]
Hi @gquintard! I'll try to look closer at this tomorrow, but just to understand a little bit the use case:

- How are those rules stores in Redis? (i.e. a list? a hash? anything else?).

- What Redis command do you plan to execute in order to retrieve the rules? Why not doing it using an EVAL (i.e. Lua script), and then use Lua logic to compose the final string to be used in the Varnish side?

**Comment by carlosabalde** [comment]
Mmm... looking a the VTC I think I have the answer to some of my questions in there: you plan to use a Redis list and the `LRANGE` command. But again, personally I think I'd use a Lua script with `EVAL` in order to do the `LRANGE` + data transformation. Have you considered it?

**Comment by gquintard** [comment]
Hi @carlosabalde,

I didn't know this was an option! It looks like it could work without touching anything here. Let me test and possibly close this PR is it works.

Thanks for the super quick reply1

**Comment by gquintard** [comment]
Thank you @carlosabalde for pointing me in the right direction. If anyone needs that code snippet:

```
	db.command("EVAL");
	db.push({"
local s = ""
for i, value in pairs(redis.call("LRANGE", KEYS[1], 0, -1)) do
	if (i > 1) then
		s = s .. ", "
	end
	s = s .. value
end
return s
"});
	db.push("1");
	db.push("mylist");
	db.execute();

        set resp.http.list = db.get_string_reply();
```

I'll lose this

**Pull request closed without merging**
