### PR TITLE
introduce .easy_execute() 2: electric boogaloo

### PR DESCRIPTION
**Pull request by gquintard**
Alright, let's try #48 again, with more experience and tests.

I'm not super happy with the `vcc` verbosity and the C redundancy, but the `vcl` code looks pretty good

I'll check if I can port that to `6.0-lts`, but `4.x` is out of the question as it doesn't support arg structs. `master` is trivial as you said and I'll also take care of it if this passes muster.

@carlosabalde, does that work for you?

### CODE REVIEW

**Comment by carlosabalde** [comment]
I wasn't aware of arg structs! Your approach is very enlightening and looks perfect to me. All my feedback is going to be nitpicking:
- Tabs are not used in this implementation, but some have been added to the `.vcc`, `.c` & `.vtc` files.
- In the `.vcc` file, you have used single quotes (i.e. `) instead of double ones (i.e. ``) to enclose keywords.
- I suggest adding in `README.md` a reference to the new method, for example in the `# Command execution` block.

Thanks!

**Comment by gquintard** [comment]
Perfectly valid nitpicking, I'll tweak the pr

**Comment by carlosabalde** [comment]
Perfect. Thanks a lot! Already squashed + merged into `7.2-dev` & cherry picked into `master`. Do you think this can be ported to `6.0-dev` (I'm not familiar with arg structs, so not sure if it's doable)?

**Comment by gquintard** [comment]
yes, that should be doable, I'll give it a shot this week

**Pull request merged**
